### ISSUE TITLE
Live update

### ISSUE THREAD

**Issue by JmiXIII** [gristlabs/custom-charts-widget#1]
Hello,

This is great widget.
Is it possible to have a live update when the data are selected from another view ?
I have tried with chart -> it updates correctly (if I select another field in the parent view, data are refered to this field and charts updates well)
With custom-charts-widget -> I have to reload the page to have the chart updated with the parent view.

**Comment by alexmojaki** [comment]
Hi, sorry I'm only seeing this now. I'm afraid I don't understand what you mean. Can you show me an example?

**Comment by alexmojaki** [comment]
Ah, I've seen the problem, it was a quirk of how the whole thing was deployed in production. Live updates should work now.

**Comment by JmiXIII** [comment]
Hello,

No problem for the delay !
Confirm it is working perfectly now, thanks for the update.

Note : I do not know but if we could have in histogram a Kernel Density Estimator trace option, it would be a very plus (like seaborn).

**Comment by alexmojaki** [comment]
This widget is a wrapper around https://github.com/plotly/react-chart-editor, and is unlikely to add any plotting-related features not provided by that library. I think your best bet would be the Jupyterlite widget: https://github.com/gristlabs/jupyterlite-widget/blob/main/USAGE.md
